{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "react-native",
    "version": "0.67.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.67.3.aar",
          "url": "react-native-0.67.3.aar",
          "size": 17797340,
          "sha512": "ae83a1a6e6129cfaa91d107cc48c2969a29aaffe94dca98a3a7824c85a9d5471a54b8386df2676705c1f9b2c06e00143c453cd4f7867f74796ddd9d30b67d285",
          "sha256": "4e8f8206697951af636ce4b270f2cf66e210d998a773b850f1c09003596c5dbd",
          "sha1": "c4d418bf8de13d78fa8f78430c9f6d3a4f815f3f",
          "md5": "db8d09fc4169801bdc2af69a38a1f7f4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.67.3.aar",
          "url": "react-native-0.67.3.aar",
          "size": 17797340,
          "sha512": "ae83a1a6e6129cfaa91d107cc48c2969a29aaffe94dca98a3a7824c85a9d5471a54b8386df2676705c1f9b2c06e00143c453cd4f7867f74796ddd9d30b67d285",
          "sha256": "4e8f8206697951af636ce4b270f2cf66e210d998a773b850f1c09003596c5dbd",
          "sha1": "c4d418bf8de13d78fa8f78430c9f6d3a4f815f3f",
          "md5": "db8d09fc4169801bdc2af69a38a1f7f4"
        }
      ]
    }
  ]
}
